In [1]:
pip install numpy


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# custom function

account_balances = [250, 895, 784, 4845, 5700, 874, 1900]

In [8]:
# calculate the Average Account balance per Customer

mean = sum(account_balances) / len(account_balances)
print(mean)

2178.285714285714


In [15]:
# let's define a custom function to calculate the mean

def mean(x):
    mean = sum(x) / len(x) # the mean variable only exists INSIDE the function, thus Local Variable
    return mean


In [16]:
mean(account_balances)

2178.285714285714

In [17]:
customer_ages = [51, 18, 25, 35, 47, 60, 29, 32]

In [18]:
mean(customer_ages)

37.125

In [19]:
# Define a custom function to calculate the MEDIAN value of a list

def median(x):
    x.sort()

    if len(x) % 2 == 0: # list is even if remainder when divided by 1 is 0
        median = (x[len(x)//2] + x[len(x)//2 - 1])/2
    else:
        median = x[len(x)//2]
    return median


In [20]:
median(account_balances)

895

In [21]:
median(customer_ages)

33.5

In [22]:
print(mean(account_balances), median(account_balances))
print(np.mean(account_balances), np.median(account_balances))


2178.285714285714 895
2178.285714285714 895.0


In [23]:
# creating arrays
array1 = np.array(account_balances)


In [24]:
print(account_balances)
print(array1)

[250, 784, 874, 895, 1900, 4845, 5700]
[ 250  784  874  895 1900 4845 5700]


In [25]:
print(type(account_balances))
print(type(array1))

<class 'list'>
<class 'numpy.ndarray'>


In [26]:
array1

array([ 250,  784,  874,  895, 1900, 4845, 5700])

In [28]:
print(array1)
print(array1)

[ 250  784  874  895 1900 4845 5700]
[ 250  784  874  895 1900 4845 5700]


In [30]:
# check the shape of the array
array1.shape

(7,)

In [31]:
# size parameter tells you how many values are in the array
array1.size

7

In [32]:
# let's look at 2 dim example
array_2d = np.array([[1,8,5,9,4],[4,7,6,2,5]])

In [33]:
print(array_2d.shape) # should return (2,5) which means 2 rows, 5 columns
print(array_2d.size) # should return 10, which is the product of rows * columns, or 2*5

(2, 5)
10


In [34]:
array_2d

array([[1, 8, 5, 9, 4],
       [4, 7, 6, 2, 5]])

In [35]:
print(array_2d)

[[1 8 5 9 4]
 [4 7 6 2 5]]


In [36]:
# Create a 3-d array
array_3d = np.array([[[1,2,3],[4,5,6]], [[12,11,10], [9,8,7]]])

In [38]:
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[12 11 10]
  [ 9  8  7]]]


In [39]:
# Create a 4-d array
array_4d = np.array([[[[1,2,3],[4,5,6]], [[12,11,10], [9,8,7]]],[[[1,2,3],[4,5,6]], [[12,11,10], [9,8,7]]]])

In [40]:
print(array_4d)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[12 11 10]
   [ 9  8  7]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[12 11 10]
   [ 9  8  7]]]]


In [41]:
print(array_3d.shape)
print(array_3d.size)

(2, 2, 3)
12


In [42]:
print(array_4d.shape)
print(array_4d.size)

(2, 2, 2, 3)
24


In [49]:
# reshaping the 3d array
array_3d.reshape(1,12).shape

(1, 12)

In [51]:
array_3d.reshape(12,1).shape

(12, 1)

In [52]:
# reshaping the 3d array
array_3d.reshape(2,6).shape

(2, 6)

In [53]:
array_3d.reshape(6,2).shape

(6, 2)

In [54]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[12, 11, 10],
        [ 9,  8,  7]]])

In [45]:
# reshaping the 3d array
array_3d.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12, 11, 10],
       [ 9,  8,  7]])

In [46]:
# reshaping the 3d array
array_3d.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6, 12, 11],
       [10,  9,  8,  7]])

In [47]:
# reshaping the 3d array
array_3d.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [12],
       [11],
       [10],
       [ 9],
       [ 8],
       [ 7]])

In [48]:
# reshaping the 3d array
array_3d.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [12, 11],
       [10,  9],
       [ 8,  7]])

In [56]:
array_4d.size

24

In [58]:
array_4d.reshape(12,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [12, 11],
       [10,  9],
       [ 8,  7],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [12, 11],
       [10,  9],
       [ 8,  7]])

In [59]:
# convert 4d array to 3d array
array_4d.reshape(2,6,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [12, 11],
        [10,  9],
        [ 8,  7]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [12, 11],
        [10,  9],
        [ 8,  7]]])

In [63]:
# convert to different style of 4d array
array_4d.reshape(3,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [12, 11]]],


       [[[10,  9],
         [ 8,  7]],

        [[ 1,  2],
         [ 3,  4]]],


       [[[ 5,  6],
         [12, 11]],

        [[10,  9],
         [ 8,  7]]]])

In [64]:
# you can set the last dimension as -1 and Python will figure it out
array_4d.reshape(2,2,2,-1)

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[12, 11, 10],
         [ 9,  8,  7]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[12, 11, 10],
         [ 9,  8,  7]]]])

In [65]:
# this is commonly used notation also when reshaping into 1 dim array, because we know we want 1 column, but may not know how many rows that is
array_4d.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [12],
       [11],
       [10],
       [ 9],
       [ 8],
       [ 7],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [12],
       [11],
       [10],
       [ 9],
       [ 8],
       [ 7]])

In [66]:
pip install matplotlib


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [67]:
import matplotlib.pyplot as plt

In [68]:
height, width = 300, 300
channels = 3

In [69]:
image = np.zeros((height, width, channels), dtype=np.uint8)

In [70]:
image.shape

(300, 300, 3)

In [71]:
image

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [72]:
plt.imshow(image)

In [93]:
image[50:100, 50:100, :] = [255, 0, 0]
image[50:100, 125:175,:] = [0,255,0]
image[50:100, 200:250,:] = [0,0,255]

In [94]:
plt.imshow(image)

In [96]:
# let's review slicing
image.shape

(300, 300, 3)

In [99]:
image[0,0,:] = [255,152,68]

In [103]:
#plt.figure(figsize=(100,100))
plt.imshow(image)

In [106]:
plt.imshow(image+150)

In [108]:
image

array([[[255, 152,  68],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [110]:
array1 + 150

array([ 400,  934, 1024, 1045, 2050, 4995, 5850])

In [111]:
array1 / 2

array([ 125. ,  392. ,  437. ,  447.5,  950. , 2422.5, 2850. ])

In [112]:
array1 // 2

array([ 125,  392,  437,  447,  950, 2422, 2850])

In [116]:
array1*2

array([  500,  1568,  1748,  1790,  3800,  9690, 11400])

In [115]:
array1 ** 2

array([   62500,   614656,   763876,   801025,  3610000, 23474025,
       32490000])

In [117]:
# array combinations (math operations on two array)

In [118]:
array_2d

array([[1, 8, 5, 9, 4],
       [4, 7, 6, 2, 5]])

In [119]:
array_2d_second = np.array([[1,5,8,9,8],[1,4,5,2,3]])
array_2d_third = np.array([[5,8,7],[4,7,5]])

In [120]:
array_2d + array_2d_second

array([[ 2, 13, 13, 18, 12],
       [ 5, 11, 11,  4,  8]])

In [121]:
# we can't add these two arrays together because they don't have the same number of dimensions
array_2d + array_2d_third

ValueError: operands could not be broadcast together with shapes (2,5) (2,3) 

In [123]:
# can't add these either because the 1d array has 6 digits, instead of 5
array_2d + array_2d_third.reshape(1,-1)

ValueError: operands could not be broadcast together with shapes (2,5) (1,6) 

In [124]:
# also can't add this because the 1d array technically is 2 dimensions with 6 rows and 1 column
array_2d + array_2d_third.reshape(-1,1)

ValueError: operands could not be broadcast together with shapes (2,5) (6,1) 

In [125]:
# as long as the second array has 1 dimension AND it matches one of the dimensions of the first array, you can broadcast
array_1d_5 = np.array([1,2,5,8,9])

In [128]:
print(array_2d)
print(array_1d_5)

[[1 8 5 9 4]
 [4 7 6 2 5]]
[1 2 5 8 9]


In [126]:
array_2d + array_1d_5

array([[ 2, 10, 10, 17, 13],
       [ 5,  9, 11, 10, 14]])

In [130]:
array_2d + array_1d_5.reshape(5,1)

ValueError: operands could not be broadcast together with shapes (2,5) (5,1) 

In [131]:
array_1d_5.reshape(5,1)

array([[1],
       [2],
       [5],
       [8],
       [9]])

In [132]:
array_2d

array([[1, 8, 5, 9, 4],
       [4, 7, 6, 2, 5]])

In [133]:
# either number of columns needs to match, or num rows needs to match when broadcasting
array_2d_new = np.array([[1],[2]])
array_2d_new

array([[1],
       [2]])

In [134]:
array_2d + array_2d_new

array([[ 2,  9,  6, 10,  5],
       [ 6,  9,  8,  4,  7]])

In [136]:
# array methods include common math operations, like sum(), mean(), std()
array_2d.sum()

51

In [137]:
array_2d.mean()

5.1

In [139]:
array_2d.std()

2.3853720883753127

In [140]:
np.median(array_2d)

5.0

In [141]:
# insert() and append()

# to append values along the COLUMNS (i.e., to the right of the array) use axis=1
np.append(array_2d, array_2d_new, axis=1)

array([[1, 8, 5, 9, 4, 1],
       [4, 7, 6, 2, 5, 2]])

In [142]:
array_2d

array([[1, 8, 5, 9, 4],
       [4, 7, 6, 2, 5]])

In [143]:
array_2d_new

array([[1],
       [2]])

In [148]:
# to append something to the bottom, we need use axis=0, and the # columns & rows must match
np.append(array_2d, [[1,25,4,5,7],[1,8,7,9,5]], axis=0)

array([[ 1,  8,  5,  9,  4],
       [ 4,  7,  6,  2,  5],
       [ 1, 25,  4,  5,  7],
       [ 1,  8,  7,  9,  5]])

In [147]:
array_1d_5

array([1, 2, 5, 8, 9])

In [149]:
# insert value based on position
np.insert(array_1d_5, 0, 15)

array([15,  1,  2,  5,  8,  9])

In [158]:
# example below: specify array, position to insert (e.g., 1 = second position), new row to insert, axis=0 (along rows)
np.insert(array_2d, 1, [5,8,9,7,5], axis=0)

array([[1, 8, 5, 9, 4],
       [5, 8, 9, 7, 5],
       [4, 7, 6, 2, 5]])

In [152]:
array_2d

array([[1, 8, 5, 9, 4],
       [4, 7, 6, 2, 5]])