In [1]:
# defining custom functions
list1 = [5,8,9,15,35,52,26,4,20]

In [2]:
# let's calculate descriptive statistics about the list

mean_list1 = sum(list1) / len(list1)
mean_list1

19.333333333333332

In [15]:
# let's define a custom function for the mean

def mean(input_list):
    mean = sum(input_list) / len(input_list)
    return mean

In [16]:
# Once a function has been defined, we can apply it directly to our list
mean(list1)

19.333333333333332

In [5]:
sum(list1)

174

In [31]:
# define a function to calculate the median of a list
# logic: 
# 1 - sort the list in ascending order, calculate length of list
# 2 - check if there's an even number of numbers, or an odd number of numbers
# 3 - if it's even > take the avg of the two in the middle; if odd, just take the middle number


def median(input_list):
    input_list.sort()
    length = len(input_list)
    if length % 2 == 0: # for even number of numbers
        # first position
        first_position = input_list[length//2]
        second_position = input_list[length//2-1]
        median = (first_position + second_position) / 2
    else: # for odd number of numbers
        median = input_list[length//2]
    return median

In [32]:
median(list1)

17.5

In [42]:
# Let's define a function to calculate standard deviation

def stdev(input_list):
    squared_list = []
    n = len(input_list)
    mean = sum(input_list) / n
    for i in input_list:
        squared_list.append((i-mean)**2)
    sq_sum = sum(squared_list)
    variance = sq_sum / n
    stdev = variance ** (1/2)
    return stdev


In [48]:
stdev(list1)

14.333527130472806

In [49]:
# rolling standard deviation
for i in range(len(list1)):
    print(stdev(list1[i:]))

14.333527130472806
14.093164440629268
13.654211804421374
13.232612773610755
12.320939718850815
11.855800268223145
11.800423721205947
10.780641085864152
8.5
0.0


In [37]:
# example of using break statement to interrupt a loop

x = 0

while x < 100:
    if x > 50:
        break
    else:
        x += 10
    print(x)

10
20
30
40
50
60


In [52]:
def descriptive_statistics(input_list):
    input_list.sort()
    length = len(input_list)
    if length % 2 == 0: # for even number of numbers
        # first position
        first_position = input_list[length//2]
        second_position = input_list[length//2-1]
        median = (first_position + second_position) / 2
    else: # for odd number of numbers
        median = input_list[length//2]
    
    mean = sum(input_list) / len(input_list)
    
    squared_list = []
    n = len(input_list)
    mean = sum(input_list) / n
    for i in input_list:
        squared_list.append((i-mean)**2)
    sq_sum = sum(squared_list)
    variance = sq_sum / n
    stdev = variance ** (1/2)

    print("Min: ", min(input_list))
    print("Max: ", max(input_list))
    print("Mean: ", mean)
    print("Median: ", median)
    print("Variance: ", variance)
    print("StDev: ", stdev)
    

In [53]:
descriptive_statistics(list1)

Min:  4
Max:  52
Mean:  19.5
Median:  17.5
Variance:  205.45
StDev:  14.333527130472806


In [54]:
list2 = [78,76,98,56,78,97,65,43,32]

In [55]:
descriptive_statistics(list2)

Min:  32
Max:  98
Mean:  69.22222222222223
Median:  76
Variance:  451.72839506172846
StDev:  21.253903054773925


### NumPy

In [58]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [59]:
import numpy as np

In [60]:
# let's create a 1-dimensional array

array_1d = np.array(list1)

In [61]:
array_1d

array([ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52])

In [62]:
# calculate the max()
array_1d.max()

52

In [63]:
# calculate the min()
array_1d.min()

4

In [64]:
# calculate the mean()
array_1d.mean()

19.5

In [65]:
# calculate the standard deviation
array_1d.std()

14.333527130472806

In [66]:
# create a 2-dimensional array

array_2d = np.array([list1,list1])

In [67]:
array_2d

array([[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
       [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]])

In [68]:
array_2d.min()

4

In [69]:
array_2d.max()

52

In [70]:
array_2d.mean()

19.5

In [71]:
# check the number of dimensions
array_2d.ndim

2

In [72]:
array_1d.ndim

1

In [73]:
# add 5 dimensions
array_5d = np.array([1,2,5,6,8], ndmin=5)

In [74]:
array_5d

array([[[[[1, 2, 5, 6, 8]]]]])

In [75]:
# add 3 dimensions
array_3d = np.array([1,2,5,6,8], ndmin=3)

In [76]:
array_3d

array([[[1, 2, 5, 6, 8]]])

In [79]:
# slicing arrays
list1[0:3]

[4, 5, 8]

In [81]:
# slicing a 1d array is basically the same as slicing a list
array_1d[0]

4

In [82]:
# slicing a 2d array, we need to specify position based on dimension
array_2d

array([[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
       [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]])

In [84]:
array_2d[0,-3]

26

In [87]:
# 3d array
array_3d = np.array([[list1,list1],[list1,list1]])

In [88]:
array_3d

array([[[52, 35, 26, 21, 20, 15,  9,  8,  5,  4],
        [52, 35, 26, 21, 20, 15,  9,  8,  5,  4]],

       [[52, 35, 26, 21, 20, 15,  9,  8,  5,  4],
        [52, 35, 26, 21, 20, 15,  9,  8,  5,  4]]])

In [90]:
array_3d[0,1,5]

15

In [97]:
# both using one set of square brackets with commas, and using square brackets for each slice are valid notations
array_5d[0][0][0][0][2]

5

In [99]:
# we can also slice ranges of values in each sub-array
array_2d[0,3:9]

array([ 9, 15, 20, 21, 26, 35])

In [100]:
# we can also slice with a step argument, like we did with lists
array_2d[0,2::2]

array([ 8, 15, 21, 35])

In [101]:
array_2d

array([[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
       [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]])

In [103]:
# we can also check the shape of an array - the shape of our 2d array is (2,10) > 2 rows, 10 columns
array_2d.shape

(2, 10)

In [106]:
array_2d.ndim

2

In [107]:
# let's check the 1d array > the tuple (10,) returns the number of columns; it will not say (1,10)
array_1d.shape

(10,)

In [108]:
array_1d

array([ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52])

In [109]:
# understanding the shape matters so we can re-shape the array
array_2d

array([[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
       [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]])

In [110]:
# in our 2d array, we have 20 values
# the possible combinations of squares are: 2x10, 5x4, 5x2x2, 1x20, 20x1, 10x2, 2x2x5, 4x5

array_2d.reshape(2,2,5)

array([[[ 4,  5,  8,  9, 15],
        [20, 21, 26, 35, 52]],

       [[ 4,  5,  8,  9, 15],
        [20, 21, 26, 35, 52]]])

In [111]:
array_2d.reshape(5,4)

array([[ 4,  5,  8,  9],
       [15, 20, 21, 26],
       [35, 52,  4,  5],
       [ 8,  9, 15, 20],
       [21, 26, 35, 52]])

In [112]:
array_2d.reshape(4,5,1)

array([[[ 4],
        [ 5],
        [ 8],
        [ 9],
        [15]],

       [[20],
        [21],
        [26],
        [35],
        [52]],

       [[ 4],
        [ 5],
        [ 8],
        [ 9],
        [15]],

       [[20],
        [21],
        [26],
        [35],
        [52]]])

In [113]:
# if we don't know one of the dimensions, we can write "-1", and Python will figure out what the size of the last dimension needs to be
array_2d.reshape(2,2,-1)

array([[[ 4,  5,  8,  9, 15],
        [20, 21, 26, 35, 52]],

       [[ 4,  5,  8,  9, 15],
        [20, 21, 26, 35, 52]]])

In [114]:
# we won't be able to use just any value we want, we need to ensure that the size (# of numbers) of the array is divisible by the dimensions 
array_2d.reshape(3,2,-1)

ValueError: cannot reshape array of size 20 into shape (3,2,newaxis)

In [115]:
# for machine learning, we often flatten the array - this creates a 1d array
array_2d.flatten()

array([ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52,  4,  5,  8,  9, 15, 20, 21,
       26, 35, 52])

In [116]:
array_2d.ravel()

array([ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52,  4,  5,  8,  9, 15, 20, 21,
       26, 35, 52])

In [119]:
# iterating through array - first, the loop will iterate through each dimension
for i in array_2d:
    print(i)

[ 4  5  8  9 15 20 21 26 35 52]
[ 4  5  8  9 15 20 21 26 35 52]


In [120]:
array_2d

array([[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
       [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]])

In [121]:
# if we need to iterate through values, we need a nested loop
for i in array_2d:
    for a in i:
        print(a)

4
5
8
9
15
20
21
26
35
52
4
5
8
9
15
20
21
26
35
52


In [123]:
# NumPy has an iteration function nditer() which can iterate through all levels within an array
for i in np.nditer(array_2d):
    print(i)

4
5
8
9
15
20
21
26
35
52
4
5
8
9
15
20
21
26
35
52


In [124]:
# We can specificy slices or steps at which to iterate; for example, taking every other value in an array
for i in np.nditer(array_2d[:,::2]):
    print(i)

4
8
15
21
35
4
8
15
21
35


In [125]:
list1

[52, 35, 26, 21, 20, 15, 9, 8, 5, 4]

In [126]:
# we can use the enumerate() function in Python to add the position of a given value, as well as the value itself
for a,b in enumerate(list1):
    print(a)
    print(b)

0
52
1
35
2
26
3
21
4
20
5
15
6
9
7
8
8
5
9
4


In [127]:
# let's say we're multiplying and replacing values in a list - we can use enumerate instead of list.index() function

for a,b in enumerate(list1):
    list1[a] = b*2

In [128]:
list1

[104, 70, 52, 42, 40, 30, 18, 16, 10, 8]

In [129]:
# previously , we achieved the same thing using the following:
for i in list1:
    list1[list1.index(i)] = i*2

In [130]:
# NumPy also has an enumerate() function

for a,b in np.ndenumerate(array_2d):
    print(a,b)

(0, 0) 4
(0, 1) 5
(0, 2) 8
(0, 3) 9
(0, 4) 15
(0, 5) 20
(0, 6) 21
(0, 7) 26
(0, 8) 35
(0, 9) 52
(1, 0) 4
(1, 1) 5
(1, 2) 8
(1, 3) 9
(1, 4) 15
(1, 5) 20
(1, 6) 21
(1, 7) 26
(1, 8) 35
(1, 9) 52


### Combining Arrays together

In [131]:
array1 = np.array([1,5,8,9])
array2 = np.array([9,5,7,15])

In [133]:
# we can use concatenate() 
arr_final = np.concatenate([array1, array2])

In [134]:
arr_final

array([ 1,  5,  8,  9,  9,  5,  7, 15])

In [140]:
# when we work with multi-dimensional objects, we use a concept called an "axis"
# if we want to join them on top of each other, we need to set axis=1

array1 = np.array([[1,2],[3,4]])
array2 = np.array([[9,5],[5,6]])
arr_final = np.concatenate((array1,array2), axis=1) # column-wise concatenation

In [141]:
arr_final

array([[1, 2, 9, 5],
       [3, 4, 5, 6]])

In [142]:
array1

array([[1, 2],
       [3, 4]])

In [143]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[9,5],[5,6]])
arr_final = np.concatenate((array1,array2), axis=0) # row-wise concatenation
arr_final

array([[1, 2],
       [3, 4],
       [9, 5],
       [5, 6]])

In [144]:
array1

array([[1, 2],
       [3, 4]])

In [145]:
# we can use the where() function to find the position of a value in an array
np.where(array1 == 4)

(array([1]), array([1]))

In [146]:
# filter for values divisible by 2
np.where(array1%2 == 0)

(array([0, 1]), array([1, 1]))

In [147]:
# Filtering arrays > state the "where()" condition inside an array slice
array1[np.where(array1%2 == 0)]

array([2, 4])

In [148]:
array1[np.where(array1 == 4)]

array([4])

### Math operations with an array

In [150]:
# with arrays, we can perform operations on the entire array at once
array1 * 2

array([[2, 4],
       [6, 8]])

In [151]:
# NumPy uses element-wise operations to perform math transformations
array1 * array2

array([[ 9, 10],
       [15, 24]])

In [152]:
array1

array([[1, 2],
       [3, 4]])

In [153]:
array2

array([[9, 5],
       [5, 6]])

In [154]:
# your arrays have to have the same shape

array1 * array_2d

ValueError: operands could not be broadcast together with shapes (2,2) (2,10) 

In [155]:
array_2d

array([[ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52],
       [ 4,  5,  8,  9, 15, 20, 21, 26, 35, 52]])

In [157]:
# two arrays to be combined have to have the same SHAPE, even if they have the same SIZE
# SIZE refers to number of elements; SHAPE refers to how the elements are spread in the dimensions

array_2d.reshape(5,2,2) * array_2d

ValueError: operands could not be broadcast together with shapes (5,2,2) (2,10) 

In [162]:
# if one of your array is all 1s or 0s, you can broadcast this onto another array
np.array([1,1,1,1,1]) + np.array([[6,7,5,8,7],[8,9,4,5,2]])

array([[ 7,  8,  6,  9,  8],
       [ 9, 10,  5,  6,  3]])

### Generating Random Values with Arrays

In [165]:
# generate random integer
x = np.random.randint(100)
x

19

In [166]:
# generate random float
x = np.random.rand()
x

0.13128300362825662

In [168]:
# generate a random array
x = np.random.randint(100, size=(5))
x

array([59, 60, 89,  3, 93])

In [169]:
# generate a random array
x = np.random.randint(100, size=(3,5))
x

array([[26, 30, 42, 91, 39],
       [99, 63, 59, 45, 47],
       [64, 58, 89, 51, 32]])

In [171]:
# generate a dataset from a normal distribution
# use loc parameter to set the mean, scale to set the stdev, size to set the size of the array
x = np.random.normal(loc=1, scale=2, size=(2,3))
x

array([[2.08273783, 0.14618065, 1.71857274],
       [1.01599777, 1.33511841, 1.27511132]])

In [173]:
# generate data samples from a uniform distribution
x = np.random.uniform(size=(2,3))
x

array([[0.01154123, 0.07389343, 0.37787668],
       [0.34854648, 0.16899364, 0.97683514]])